

import urllib.request

def download_all(df):
    """
    Download files
    Download all files in dataframe generated by cmip6_search

    Parameters
    -------------
    df: pandas dataframe
        A dataframe generated by cmip6_search


    -------------

    """
    for i in range(0, len(df)):
        urllib.request.urlretrieve(df.url[i], df.file[i])




